src/tutorial/site_admin/urls.py
from django.conf.urls import url
from tutorial.site_admin.views import CategoryCreateView, CategoryListView,\
     CategoryEditView, CategoryDeleteView

urlpatterns = [
    url(r"^category/$", CategoryListView.as_view(), name="category_list"),
    url(r"^category/(?P<category_id>\d+)/$", CategoryEditView.as_view(), name="category_edit"),
    url(r"^category/(?P<category_id>\d+)/delete/$", CategoryDeleteView.as_view(), name="category_delete"),
    url(r"^category/create/$", CategoryCreateView.as_view(), name="category_create"),
]

src/tutorial/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth.views import login, logout
from django.shortcuts import render


admin.autodiscover()

urlpatterns = [
    url(r'^$', lambda request: render(request, "index.html"), name="index"),
    url(r'^todo/', include('tutorial.todo.urls', namespace="todo")),
    url(r'^master/', include('tutorial.master.urls', namespace="master")),
    url(r'^admin/', include('tutorial.site_admin.urls', namespace="site_admin")),
    url(r'^admin/native/', include(admin.site.urls)),

    url(r'^login/$', login, name="login", kwargs={'template_name': 'login.html'}),
    url(r'^logout/$', logout, name="logout", kwargs={"next_page": 'index'}),
]

src/tutorial/site_admin/models.py
from django.db import models

# Create your models here.

src/tutorial/site_admin/forms.py
from django import forms

from django_cbv_utils.forms import SetFromControlMixin
from tutorial.master.models import Category


class CategoryCreateForm(forms.ModelForm, SetFromControlMixin):

    class Meta:
        model = Category
        fields = [
            'order',
            'name',
        ]


class CategoryEditForm(forms.ModelForm, SetFromControlMixin):

    class Meta:
        model = Category
        fields = [
            'enabled',
            'order',
            'name',
        ]

src/tutorial/site_admin/views.py
from django.views.generic import CreateView, ListView, UpdateView, DeleteView
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.core.urlresolvers import reverse_lazy

from tutorial.master.models import Category
from tutorial.site_admin.forms import CategoryCreateForm, CategoryEditForm
from tutorial.views import AdminLoginRequiredMixin


class CategoryCreateView(AdminLoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Category
    form_class = CategoryCreateForm
    success_url = reverse_lazy('site_admin:category_list')
    template_name = "site_admin/category/create.html"
    success_message = "登録しました。"


class CategoryListView(AdminLoginRequiredMixin, ListView):
    model = Category
    template_name = "site_admin/category/list.html"
    context_object_name = "category_list"
    paginate_by = 10


class CategoryEditView(AdminLoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = Category
    form_class = CategoryEditForm
    success_url = reverse_lazy('site_admin:category_list')
    pk_url_kwarg = 'category_id'
    template_name = "site_admin/category/edit.html"
    success_message = "修正しました。"


class CategoryDeleteView(AdminLoginRequiredMixin, SuccessMessageMixin, DeleteView):
    model = Category
    success_url = reverse_lazy('site_admin:category_list')
    pk_url_kwarg = 'category_id'
    template_name = "site_admin/category/delete.html"
    success_message = "削除しました。"

    def delete(self, request, *args, **kwargs):
        messages.success(request, self.success_message)
        return super().delete(request, *args, **kwargs)

src/tutorial/site_admin/templates/site_admin/category/create.html
{% extends "base.html" %}
{% block title %}カテゴリー登録{% endblock%}

{% block content %}
<form method="post">{% csrf_token %}
  <div class="panel panel-primary">
    <div class="panel-heading">
      <h4>カテゴリー登録フォーム</h4>
    </div>
    <div class="panel-body">
      <table class="table table-bordered">
        {% for field in form %}
          <tr {% if field.errors %}class="alert-danger"{% endif %}>
            <th>{{ field.label }}</th>
            <td>{{ field.errors }}{{ field }}</td>
          </tr>
        {% endfor %}
      </table>
    </div>
    <div class="panel-footer align-center">
      <button type="submit" class="btn btn-lg btn-primary">登録</button>
    </div>
  </div>
</form>
{% endblock %}

src/tutorial/site_admin/templates/site_admin/category/delete.html
{% extends "base.html" %}
{% block title %}カテゴリー削除{% endblock%}

{% block content %}
<form method="post">{% csrf_token %}
  <div class="panel panel-primary">
    <div class="panel-heading">
      <h4>カテゴリー削除フォーム</h4>
    </div>
    <div class="panel-body">
      <table class="table table-bordered">
        <tr><th>表示順</th><td>{{ category.order }}</td></tr>
        <tr><th>名称</th><td>{{ category.name }}</td></tr>
        <tr><th>作成日時</th><td>{{ category.created }}</td></tr>
        <tr><th>更新日時</th><td>{{ category.updated }}</td></tr>
        <tr><th>有効</th><td>{% if category.enabled %}有効{% else %}無効{% endif %}</td></tr>
      </table>
    </div>
    <div class="panel-footer align-center">
      <button type="submit" class="btn btn-lg btn-danger">削除</button>
    </div>
  </div>
</form>
{% endblock %}

src/tutorial/site_admin/templates/site_admin/category/edit.html
{% extends "base.html" %}
{% block title %}カテゴリー修正{% endblock%}

{% block content %}
<form method="post">{% csrf_token %}
  <div class="panel panel-primary">
    <div class="panel-heading">
      <h4>カテゴリー修正フォーム</h4>
    </div>
    <div class="panel-body">
      <table class="table table-bordered">
        {% for field in form %}
          <tr {% if field.errors %}class="alert-danger"{% endif %}>
            <th>{{ field.label }}</th>
            <td>{{ field.errors }}{{ field }}</td>
          </tr>
        {% endfor %}
      </table>
    </div>
    <div class="panel-footer align-center">
      <button type="submit" class="btn btn-lg btn-primary">修正</button>
    </div>
  </div>
</form>
{% endblock %}

src/tutorial/site_admin/templates/site_admin/category/list.html
{% extends "base.html" %}
{% block title %}カテゴリー一覧{{ is_paginated }}{% endblock%}

{% block content %}
<table class="table table-bordered">
  <thead>
    <tr>
      <th>表示順</th>
      <th>名称</th>
      <th>作成日時</th>
      <th>更新日時</th>
      <th>有効</th>
      <th>修正</th>
      <th>削除</th>
    </tr>
  </thead>
  <tbody>
    {% for category in category_list %}
    <tr>
      <td>{{ category.order }}</td>
      <td>{{ category.name }}</td>
      <td>{{ category.created }}</td>
      <td>{{ category.updated }}</td>
      <td>{% if category.enabled %}有効{% else %}無効{% endif %}</td>
      <td>
        <a href="{% url "site_admin:category_edit" category.id %}">
          <button class="btn btn-default" type="button">修正</button>
        </a>
      </td>
      <td>
        <a href="{% url "site_admin:category_delete" category.id %}">
          <button class="btn btn-danger" type="button">削除</button>
        </a>
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% if is_paginated %}
<div class="pagination" style="float:right">
  <span class="page-links">
    {% if page_obj.has_previous %}
    <a href="{% url "site_admin:category_list" %}?page={{ page_obj.previous_page_number }}">previous</a>
    {% endif %}
    <span class="page-current">
      Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
    </span>
    {% if page_obj.has_next %}
    <a href="{% url "site_admin:category_list" %}?page={{ page_obj.next_page_number }}">next</a>
    {% endif %}
  </span>
</div>
{% endif %}
{% endblock %}