src/tutorial/todo/urls.py
from django.conf.urls import url
from tutorial.todo.views import ToDoUserCreateView, ToDoCreateView,\
     ToDoListView, ToDoDetailView, ToDoEditView

urlpatterns = [
    url(r"^$", ToDoListView.as_view(), name="list"),
    url(r"^(?P<todo_id>\d+)/$", ToDoDetailView.as_view(), name="detail"),
    url(r"^(?P<todo_id>\d+)/edit$", ToDoEditView.as_view(), name="edit"),
    url(r"^create/$", ToDoCreateView.as_view(), name="create"),
    url(r"^user/create/$", ToDoUserCreateView.as_view(), name="user_create"),
]

src/tutorial/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth.views import login, logout
from django.shortcuts import render


admin.autodiscover()

urlpatterns = [
    url(r'^$', lambda request: render(request, "index.html"), name="index"),
    url(r'^todo/', include('tutorial.todo.urls', namespace="todo")),
    url(r'^master/', include('tutorial.master.urls', namespace="master")),
    url(r'^admin/', include('tutorial.site_admin.urls', namespace="site_admin")),
    url(r'^admin/native/', include(admin.site.urls)),

    url(r'^login/$', login, name="login", kwargs={'template_name': 'login.html'}),
    url(r'^logout/$', logout, name="logout", kwargs={"next_page": 'index'}),
]

src/tutorial/todo/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from tutorial.master.models import Category
from tutorial.models import ModelBase


class ToDoUser(User):
    """ユーザー"""

    class Meta:
        verbose_name = verbose_name_plural = "ToDoUser"
        ordering = ["-date_joined"]

    handle_name = models.CharField("表示名", max_length=255)

    def __str__(self):
        return self.handle_name


class ToDo(ModelBase):
    """ToDo"""

    class Meta:
        verbose_name = verbose_name_plural = "ToDo"

    user = models.ForeignKey(ToDoUser, verbose_name="ユーザー")
    categories = models.ManyToManyField(Category, verbose_name="カテゴリー")

    name = models.CharField("名称", max_length=255)
    deadline = models.DateTimeField("締め切り")
    completed = models.DateTimeField("完了日時", null=True, blank=True)

    PRIORITY_HIGH = 1
    PRIORITY_MIDDLE = 2
    PRIORITY_LOW = 3
    PRIORITY_CHOICES = (
        (PRIORITY_HIGH, "高"),
        (PRIORITY_MIDDLE, "中"),
        (PRIORITY_LOW, "低"),
    )
    priority = models.PositiveIntegerField("優先度", choices=PRIORITY_CHOICES)
    note = models.TextField("備考", blank=True)

    def __str__(self):
        return self.name

    @property
    def is_completed(self):
        return self.completed is not None

    def complete(self):
        self.completed = timezone.now()
        self.save()

    def get_categories_display(self):
        return " ".join([c.name for c in self.categories.all()])

src/tutorial/todo/forms.py
from django import forms
from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import UserCreationForm

from django_cbv_utils.forms import SetFromControlMixin, SetDateTimePickerMixin
from tutorial.master.models import Category
from tutorial.todo.models import ToDoUser, ToDo


class ToDoUserCreateForm(UserCreationForm, SetFromControlMixin):
    email = forms.EmailField(label="メールアドレス", required=True)
    username = forms.RegexField(
        label="ユーザー名",
        max_length=15,
        regex=r'^[a-zA-Z0-9]+$',
        error_messages={'invalid': "半角英数15字以内で入力してください。"})

    class Meta:
        model = ToDoUser
        fields = [
            "username",
            "password1",
            "password2",
            "handle_name",
            "email",
        ]

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop("request")
        super().__init__(*args, **kwargs)

    def save(self, commit=True):
        todouser = super().save(commit)
        if commit:
            user = authenticate(
                username=self.cleaned_data["username"],
                password=self.cleaned_data["password1"])
            if user is not None and user.is_active:
                    login(self.request, user)
        return todouser


class ToDoCreateForm(forms.ModelForm, SetFromControlMixin, SetDateTimePickerMixin):

    class Meta:
        model = ToDo
        fields = [
            "name",
            "deadline",
            "priority",
            "categories",
            "note",
        ]
        widgets = {
            'categories': forms.CheckboxSelectMultiple()
        }

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop("request")
        super().__init__(*args, **kwargs)
        self.fields['categories'].queryset = Category.objects.filter(enabled=True)
        self.fields['categories'].widget.attrs.update({'class': "checkbox"})

    def save(self, commit=True):
        todo = super().save(commit=False)
        todo.user = self.request.user.todouser
        if commit:
            todo.save()
            self.save_m2m()
        return todo


class ToDoEditForm(forms.ModelForm, SetFromControlMixin, SetDateTimePickerMixin):

    class Meta:
        model = ToDo
        fields = [
            "completed",
            "name",
            "deadline",
            "priority",
            "categories",
            "note",
        ]
        widgets = {
            'categories': forms.CheckboxSelectMultiple()
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['categories'].queryset = Category.objects.filter(enabled=True)
        self.fields['categories'].widget.attrs.update({'class': "checkbox"})

src/tutorial/todo/views.py
from django.views.generic import CreateView, ListView, DetailView, UpdateView
from django.contrib.messages.views import SuccessMessageMixin
from django.core.urlresolvers import reverse_lazy

from tutorial.todo.models import ToDoUser, ToDo
from tutorial.todo.forms import ToDoUserCreateForm, ToDoCreateForm, ToDoEditForm
from tutorial.views import LoginRequiredMixin


class ToDoUserCreateView(SuccessMessageMixin, CreateView):
    model = ToDoUser
    form_class = ToDoUserCreateForm
    success_url = reverse_lazy('index')
    template_name = "todo/user_create.html"
    success_message = "登録しました。"

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update({"request": self.request})
        return kwargs


class ToDoCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = ToDo
    form_class = ToDoCreateForm
    success_url = reverse_lazy('todo:list')
    template_name = "todo/create.html"
    success_message = "登録しました。"

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update({"request": self.request})
        return kwargs


class ToDoListView(LoginRequiredMixin, ListView):
    model = ToDo
    template_name = "todo/list.html"
    context_object_name = "todo_list"
    paginate_by = 10

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(user__id=self.request.user.id)
        return queryset


class ToDoDetailView(LoginRequiredMixin, DetailView):
    model = ToDo
    pk_url_kwarg = "todo_id"
    template_name = "todo/detail.html"


class ToDoEditView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = ToDo
    form_class = ToDoEditForm
    pk_url_kwarg = "todo_id"
    template_name = "todo/edit.html"
    success_message = "修正しました。"

    def get_success_url(self):
        return reverse_lazy('todo:detail', args=(self.object.id,))

src/tutorial/todo/templates/todo/create.html
{% extends "base.html" %}
{% block title %}ToDo登録{% endblock%}

{% block content %}
<form method="post">{% csrf_token %}
  <div class="panel panel-primary">
    <div class="panel-heading">
      <h4>ToDo登録フォーム</h4>
    </div>
    <div class="panel-body">
      <table class="table table-bordered">
        {% for field in form %}
          <tr {% if field.errors %}class="alert-danger"{% endif %}>
            <th>{{ field.label }}</th>
            <td>{{ field.errors }}
              {% if field == form.categories %}
                <div class="checkbox">{{ field }}</div>
              {% else %}
                {{ field }}
              {% endif %}
            </td>
          </tr>
        {% endfor %}
      </table>
    </div>
    <div class="panel-footer align-center">
      <button type="submit" class="btn btn-lg btn-primary">登録</button>
    </div>
  </div>
</form>
{% endblock %}

src/tutorial/todo/templates/todo/detail.html
{% extends "base.html" %}
{% block title %}ToDo詳細{% endblock%}

{% block content %}
<div class="panel panel-primary">
  <div class="panel-heading">
    <h4>ToDo詳細</h4>
  </div>
  <div class="panel-body">
    <table class="table table-bordered">
      <tr>
        <th>完了</th>
        <td>{% if todo.is_completed %}{{ todo.completed }}{% else %}未完了{% endif %}</td>
      </tr>
      <tr>
        <th>締め切り</th>
        <td>{{ todo.deadline }}</td>
      </tr>
      <tr>
        <th>名称</th>
        <td>{{ todo.name }}</td>
      </tr>
      <tr>
        <th>優先度</th>
        <td>{{ todo.get_priority_display }}</td>
      </tr>
      <tr>
        <th>カテゴリー</th>
        <td>{{ todo.get_categories_display }}</td>
      </tr>
      <tr>
        <th>作成日時</th>
        <td>{{ todo.created }}</td>
      </tr>
      <tr>
        <th>更新日時</th>
        <td>{{ todo.updated }}</td>
      </tr>
      <tr>
        <th>有効</th>
        <td>{% if todo.enabled %}有効{% else %}無効{% endif %}</td>
      </tr>
      <tr>
        <th>備考</th>
        <td>{{ todo.note|linebreaks }}</td>
      </tr>
    </table>
  </div>
  <div class="panel-footer align-center">
    <a href="{% url "todo:edit" todo.id %}">
      <button type="button" class="btn btn-lg btn-primary">修正</button>
    </a>
  </div>
</div>
{% endblock %}

src/tutorial/todo/templates/todo/edit.html
{% extends "base.html" %}
{% block title %}ToDo修正{% endblock%}

{% block content %}
<form method="post">{% csrf_token %}
  <div class="panel panel-primary">
    <div class="panel-heading">
      <h4>ToDo修正フォーム</h4>
    </div>
    <div class="panel-body">
      <table class="table table-bordered">
        {% for field in form %}
          <tr {% if field.errors %}class="alert-danger"{% endif %}>
            <th>{{ field.label }}</th>
            <td>{{ field.errors }}
              {% if field == form.categories %}
                <div class="checkbox">{{ field }}</div>
              {% else %}
                {{ field }}
              {% endif %}
            </td>
          </tr>
        {% endfor %}
      </table>
    </div>
    <div class="panel-footer align-center">
      <button type="submit" class="btn btn-lg btn-primary">修正</button>
    </div>
  </div>
</form>
{% endblock %}

src/tutorial/todo/templates/todo/list.html
{% extends "base.html" %}
{% block title %}ToDo一覧{% endblock%}

{% block content %}
<table class="table table-bordered">
  <thead>
    <tr>
      <th>完了</th>
      <th>締め切り</th>
      <th>名称</th>
      <th>優先度</th>
      <th>カテゴリー</th>
      <th>作成日時</th>
      <th>有効</th>
      <th>詳細</th>
    </tr>
  </thead>
  <tbody>
    {% for todo in todo_list %}
    <tr>
      <td>{% if todo.is_completed %}{{ todo.completed }}{% else %}未完了{% endif %}</td>
      <td>{{ todo.deadline }}</td>
      <td>{{ todo.name }}</td>
      <td>{{ todo.get_priority_display }}
      <td>{{ todo.get_categories_display }}</td>
      <td>{{ todo.created }}</td>
      <td>{% if todo.enabled %}有効{% else %}無効{% endif %}</td>
      <td>
        <a href="{% url "todo:detail" todo.id %}">
          <button class="btn btn-default" type="button">詳細</button>
        </a>
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% if is_paginated %}
<div class="pagination" style="float:right">
  <span class="page-links">
    {% if page_obj.has_previous %}
    <a href="{% url "todo:list" %}?page={{ page_obj.previous_page_number }}">previous</a>
    {% endif %}
    <span class="page-current">
      Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
    </span>
    {% if page_obj.has_next %}
    <a href="{% url "todo:list" %}?page={{ page_obj.next_page_number }}">next</a>
    {% endif %}
  </span>
</div>
{% endif %}
{% endblock %}

src/tutorial/todo/templates/todo/user_create.html
{% extends "base.html" %}
{% block title %}新規登録{% endblock%}

{% block content %}
<form method="post">{% csrf_token %}
  <div class="panel panel-primary">
    <div class="panel-heading">
      <h4>新規登録フォーム</h4>
    </div>
    <div class="panel-body">
      <table class="table table-bordered">
        {% for field in form %}
          <tr {% if field.errors %}class="alert-danger"{% endif %}>
            <th>{{ field.label }}</th>
            <td>{{ field.errors }}{{ field }}</td>
          </tr>
        {% endfor %}
      </table>
    </div>
    <div class="panel-footer align-center">
      <button type="submit" class="btn btn-lg btn-primary">登録</button>
    </div>
  </div>
</form>
{% endblock %}