src/tutorial/master/urls.py
from django.conf.urls import url

urlpatterns = [
]

src/tutorial/site_admin/urls.py
from django.conf.urls import url
from tutorial.site_admin.views import CategoryCreateView, CategoryListView,\
     CategoryEditView, CategoryDeleteView

urlpatterns = [
    url(r"^category/$", CategoryListView.as_view(), name="category_list"),
    url(r"^category/(?P<category_id>\d+)/$", CategoryEditView.as_view(), name="category_edit"),
    url(r"^category/(?P<category_id>\d+)/delete/$", CategoryDeleteView.as_view(), name="category_delete"),
    url(r"^category/create/$", CategoryCreateView.as_view(), name="category_create"),
]

src/tutorial/todo/urls.py
from django.conf.urls import url
from tutorial.todo.views import ToDoUserCreateView, ToDoCreateView,\
     ToDoListView, ToDoDetailView, ToDoEditView

urlpatterns = [
    url(r"^$", ToDoListView.as_view(), name="list"),
    url(r"^(?P<todo_id>\d+)/$", ToDoDetailView.as_view(), name="detail"),
    url(r"^(?P<todo_id>\d+)/edit$", ToDoEditView.as_view(), name="edit"),
    url(r"^create/$", ToDoCreateView.as_view(), name="create"),
    url(r"^user/create/$", ToDoUserCreateView.as_view(), name="user_create"),
]

src/tutorial/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth.views import login, logout
from django.shortcuts import render


admin.autodiscover()

urlpatterns = [
    url(r'^$', lambda request: render(request, "index.html"), name="index"),
    url(r'^todo/', include('tutorial.todo.urls', namespace="todo")),
    url(r'^master/', include('tutorial.master.urls', namespace="master")),
    url(r'^admin/', include('tutorial.site_admin.urls', namespace="site_admin")),
    url(r'^admin/native/', include(admin.site.urls)),

    url(r'^login/$', login, name="login", kwargs={'template_name': 'login.html'}),
    url(r'^logout/$', logout, name="logout", kwargs={"next_page": 'index'}),
]

src/tutorial/master/models.py
from django.db import models
from tutorial.models import ModelBase


class Category(ModelBase):
    """カテゴリー"""

    class Meta:
        verbose_name = verbose_name_plural = "カテゴリー"
        ordering = ["order"]

    name = models.CharField("名称", max_length=255)
    order = models.PositiveIntegerField("表示順")

    def __str__(self):
        return self.name

src/tutorial/models.py
from django.db import models


class ModelBase(models.Model):

    class Meta:
        abstract = True
        ordering = ["-created"]

    created = models.DateTimeField("作成日時", auto_now_add=True)
    updated = models.DateTimeField("更新日時", auto_now=True)
    enabled = models.BooleanField("有効", default=True)

src/tutorial/site_admin/models.py
from django.db import models

# Create your models here.

src/tutorial/todo/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from tutorial.master.models import Category
from tutorial.models import ModelBase


class ToDoUser(User):
    """ユーザー"""

    class Meta:
        verbose_name = verbose_name_plural = "ToDoUser"
        ordering = ["-date_joined"]

    handle_name = models.CharField("表示名", max_length=255)

    def __str__(self):
        return self.handle_name


class ToDo(ModelBase):
    """ToDo"""

    class Meta:
        verbose_name = verbose_name_plural = "ToDo"

    user = models.ForeignKey(ToDoUser, verbose_name="ユーザー")
    categories = models.ManyToManyField(Category, verbose_name="カテゴリー")

    name = models.CharField("名称", max_length=255)
    deadline = models.DateTimeField("締め切り")
    completed = models.DateTimeField("完了日時", null=True, blank=True)

    PRIORITY_HIGH = 1
    PRIORITY_MIDDLE = 2
    PRIORITY_LOW = 3
    PRIORITY_CHOICES = (
        (PRIORITY_HIGH, "高"),
        (PRIORITY_MIDDLE, "中"),
        (PRIORITY_LOW, "低"),
    )
    priority = models.PositiveIntegerField("優先度", choices=PRIORITY_CHOICES)
    note = models.TextField("備考", blank=True)

    def __str__(self):
        return self.name

    @property
    def is_completed(self):
        return self.completed is not None

    def complete(self):
        self.completed = timezone.now()
        self.save()

    def get_categories_display(self):
        return " ".join([c.name for c in self.categories.all()])

src/tutorial/site_admin/forms.py
from django import forms

from django_cbv_utils.forms import SetFromControlMixin
from tutorial.master.models import Category


class CategoryCreateForm(forms.ModelForm, SetFromControlMixin):

    class Meta:
        model = Category
        fields = [
            'order',
            'name',
        ]


class CategoryEditForm(forms.ModelForm, SetFromControlMixin):

    class Meta:
        model = Category
        fields = [
            'enabled',
            'order',
            'name',
        ]

src/tutorial/todo/forms.py
from django import forms
from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import UserCreationForm

from django_cbv_utils.forms import SetFromControlMixin, SetDateTimePickerMixin
from tutorial.master.models import Category
from tutorial.todo.models import ToDoUser, ToDo


class ToDoUserCreateForm(UserCreationForm, SetFromControlMixin):
    email = forms.EmailField(label="メールアドレス", required=True)
    username = forms.RegexField(
        label="ユーザー名",
        max_length=15,
        regex=r'^[a-zA-Z0-9]+$',
        error_messages={'invalid': "半角英数15字以内で入力してください。"})

    class Meta:
        model = ToDoUser
        fields = [
            "username",
            "password1",
            "password2",
            "handle_name",
            "email",
        ]

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop("request")
        super().__init__(*args, **kwargs)

    def save(self, commit=True):
        todouser = super().save(commit)
        if commit:
            user = authenticate(
                username=self.cleaned_data["username"],
                password=self.cleaned_data["password1"])
            if user is not None and user.is_active:
                    login(self.request, user)
        return todouser


class ToDoCreateForm(forms.ModelForm, SetFromControlMixin, SetDateTimePickerMixin):

    class Meta:
        model = ToDo
        fields = [
            "name",
            "deadline",
            "priority",
            "categories",
            "note",
        ]
        widgets = {
            'categories': forms.CheckboxSelectMultiple()
        }

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop("request")
        super().__init__(*args, **kwargs)
        self.fields['categories'].queryset = Category.objects.filter(enabled=True)
        self.fields['categories'].widget.attrs.update({'class': "checkbox"})

    def save(self, commit=True):
        todo = super().save(commit=False)
        todo.user = self.request.user.todouser
        if commit:
            todo.save()
            self.save_m2m()
        return todo


class ToDoEditForm(forms.ModelForm, SetFromControlMixin, SetDateTimePickerMixin):

    class Meta:
        model = ToDo
        fields = [
            "completed",
            "name",
            "deadline",
            "priority",
            "categories",
            "note",
        ]
        widgets = {
            'categories': forms.CheckboxSelectMultiple()
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['categories'].queryset = Category.objects.filter(enabled=True)
        self.fields['categories'].widget.attrs.update({'class': "checkbox"})

src/tutorial/master/views.py
from django.shortcuts import render

# Create your views here.

src/tutorial/site_admin/views.py
from django.views.generic import CreateView, ListView, UpdateView, DeleteView
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.core.urlresolvers import reverse_lazy

from tutorial.master.models import Category
from tutorial.site_admin.forms import CategoryCreateForm, CategoryEditForm
from tutorial.views import AdminLoginRequiredMixin


class CategoryCreateView(AdminLoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Category
    form_class = CategoryCreateForm
    success_url = reverse_lazy('site_admin:category_list')
    template_name = "site_admin/category/create.html"
    success_message = "登録しました。"


class CategoryListView(AdminLoginRequiredMixin, ListView):
    model = Category
    template_name = "site_admin/category/list.html"
    context_object_name = "category_list"
    paginate_by = 10


class CategoryEditView(AdminLoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = Category
    form_class = CategoryEditForm
    success_url = reverse_lazy('site_admin:category_list')
    pk_url_kwarg = 'category_id'
    template_name = "site_admin/category/edit.html"
    success_message = "修正しました。"


class CategoryDeleteView(AdminLoginRequiredMixin, SuccessMessageMixin, DeleteView):
    model = Category
    success_url = reverse_lazy('site_admin:category_list')
    pk_url_kwarg = 'category_id'
    template_name = "site_admin/category/delete.html"
    success_message = "削除しました。"

    def delete(self, request, *args, **kwargs):
        messages.success(request, self.success_message)
        return super().delete(request, *args, **kwargs)

src/tutorial/todo/views.py
from django.views.generic import CreateView, ListView, DetailView, UpdateView
from django.contrib.messages.views import SuccessMessageMixin
from django.core.urlresolvers import reverse_lazy

from tutorial.todo.models import ToDoUser, ToDo
from tutorial.todo.forms import ToDoUserCreateForm, ToDoCreateForm, ToDoEditForm
from tutorial.views import LoginRequiredMixin


class ToDoUserCreateView(SuccessMessageMixin, CreateView):
    model = ToDoUser
    form_class = ToDoUserCreateForm
    success_url = reverse_lazy('index')
    template_name = "todo/user_create.html"
    success_message = "登録しました。"

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update({"request": self.request})
        return kwargs


class ToDoCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = ToDo
    form_class = ToDoCreateForm
    success_url = reverse_lazy('todo:list')
    template_name = "todo/create.html"
    success_message = "登録しました。"

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update({"request": self.request})
        return kwargs


class ToDoListView(LoginRequiredMixin, ListView):
    model = ToDo
    template_name = "todo/list.html"
    context_object_name = "todo_list"
    paginate_by = 10

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(user__id=self.request.user.id)
        return queryset


class ToDoDetailView(LoginRequiredMixin, DetailView):
    model = ToDo
    pk_url_kwarg = "todo_id"
    template_name = "todo/detail.html"


class ToDoEditView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = ToDo
    form_class = ToDoEditForm
    pk_url_kwarg = "todo_id"
    template_name = "todo/edit.html"
    success_message = "修正しました。"

    def get_success_url(self):
        return reverse_lazy('todo:detail', args=(self.object.id,))

src/tutorial/views.py
from django.contrib.auth.decorators import login_required, user_passes_test
from django.utils.decorators import method_decorator


class LoginRequiredMixin(object):

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)


class AdminLoginRequiredMixin(object):

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

src/tutorial/templates/base.html
{% load static %}
{% load i18n %}
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <title>{% block title %}ToDo管理システム{% endblock %}</title>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script>window.jQuery || document.write('<script src="{% static 'js/jquery-1.12.4.min.js' %}"><\/script>')</script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

    <!-- Bootstrap -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <style type="text/css">
      body {
        padding-top: 50px;
      }
      #main {
        padding: 40px 15px;
      }
      .align-center {
        text-align: center;
      }
      .checkbox li {
        list-style-type: none;
      }
      .checkbox ul {
        padding-left: 10px;
      }
      .asteriskField {
        color: red;
      }
    </style>
    {% if form %}
      {{ form.media }}
    {% endif %}
    {% block stylesheet %}{% endblock %}
    {% block head %}{% endblock %}
    {% block script %}{% endblock %}
  </head>
  <body>
    {% block body-header %}
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          {% block nav_title %}
          <a class="navbar-brand" href="{% url "index" %}">ToDo管理システム</a>
          {% endblock %}
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            {% block nav_body %}
              {% if user.is_authenticated %}
                {% if user.is_superuser %}
                  <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                      カテゴリー
                      <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                      <li><a href="{% url 'site_admin:category_list' %}">一覧</a></li>
                      <li><a href="{% url 'site_admin:category_create' %}">登録</a></li>
                    </ul>
                  </li>
                {% else %}
                  <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                      ToDo
                      <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                      <li><a href="{% url 'todo:list' %}">一覧</a></li>
                      <li><a href="{% url 'todo:create' %}">登録</a></li>
                    </ul>
                  </li>
                {% endif %}
              {% endif %}
            {% endblock %}
          </ul>
          <ul class="nav navbar-nav navbar-right">
            {% block nav_right %}
              {% if user.is_authenticated %}
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                    {% if user.is_superuser %}
                      管理者
                    {% else %}
                      {{ user.todouser.handle_name }}
                    {% endif %}
                    <span class="caret"></span>
                  </a>
                  <ul class="dropdown-menu">
                    <li><a href="{% url 'logout' %}">ログアウト</a></li>
                  </ul>
                </li>
              {% else %}
                <li><a href="{% url 'todo:user_create' %}">新規登録</a></li>
                <li><a href="{% url 'login' %}">ログイン</a></li>
              {% endif %}
            {% endblock %}
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>
    {% endblock %}
    <div class="container">
      {% block page-header %}
      {% endblock %}
      {% block message %}
        {% if messages %}
          {% for message in messages %}
          <div class="alert {% if message.tags %}{{ message.tags }}{% endif %}">{{ message }}</div>
          {% endfor %}
        {% endif %}
      {% endblock %}
      <div id="main">
        {% block content %}
        {% endblock %}
      </div>
    </div><!-- /.container -->
  </body>
</html>

src/tutorial/templates/index.html
{% extends "base.html" %}

{% block content %}
<div class="align-center">
  <h1>ToDo管理システム</h1>
</div>
{% endblock %}

src/tutorial/templates/login.html
{% extends "base.html" %}
{% load static %}
{% block title %}ログイン{% endblock %}

{% block script %}
<script type="text/javascript">
  $(function(){
    $("#id_username").addClass("form-control");
    $("#id_password").addClass("form-control");
  });
</script>
{% endblock %}

{% block content %}
<form method="post">{% csrf_token %}
  <div class="panel panel-primary">
    <div class="panel-heading">
    <h4>ログインフォーム</h4>
    </div>
    <table class="table table-bordered">
      <tbody{% if form.username.errors or form.password.errors %}{% elif form.errors %} class="alert-danger">
        <tr><th colspan=2>ユーザー名とパスワードが一致しませんでした。</th></tr{% endif %}>
        <tr {% if form.username.errors %}class="alert-danger"{% endif %}>
          <th>{{ form.username.label }}</th>
          <td>{{ form.username.errors }}{{ form.username }}</td>
        </tr>
        <tr {% if form.password.errors %}class="alert-danger"{% endif%}>
          <th>{{ form.password.label }}</th>
          <td>{{ form.password.errors }}{{ form.password }}</td>
        </tr>
      </tbody>
    </table>
    <div class="panel-footer align-center">
      <input class="btn btn-primary btn-lg" type="submit" value="ログイン" />
      <input type="hidden" name="next" value="{{ next }}" />
    </div>
  </div>
</form>
{% endblock %}